[package]
name = "safe_canister_upgrades"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10"
ic-cdk = { git = "https://github.com/dfinity/cdk-rs.git", rev = "1ea79d0502f9d602fec5b13d912cb9f0e7ef3a05" }
serde_bytes = "0.11.15"

[lib]
crate-type = ["cdylib"]
